<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Subkriteria_model extends CI_Model
{

    public $table = 'subkriteria';
    public $id = 'id_subkriteria';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get data by id
    function get_by_id_kriteria($id)
    {
        $this->db->where('id_kriteria', $id);
        $this->db->order_by($this->id, 'ASC');
        return $this->db->get($this->table)->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_subkriteria', $q);
    	$this->db->or_like('id_kriteria', $q);
    	$this->db->or_like('nama_subkriteria', $q);
    	$this->db->or_like('bobot_subkriteria_persen', $q);
    	$this->db->or_like('bobot_subkriteria', $q);
    	$this->db->or_like('w', $q);
    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_subkriteria', $q);
    	$this->db->or_like('id_kriteria', $q);
    	$this->db->or_like('nama_subkriteria', $q);
    	$this->db->or_like('bobot_subkriteria_persen', $q);
    	$this->db->or_like('bobot_subkriteria', $q);
    	$this->db->or_like('w', $q);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Subkriteria_model.php */
/* Location: ./application/models/Subkriteria_model.php */
/* Please DO NOT modify this information : */
/* This file generated by Andre Bhaskoro (+62 82 333 817 317) At : 2016-09-30 10:53:48 */
/* http://bhas.web.id */