<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Survey_model extends CI_Model
{

    public $table = 'survey';
    public $id = 'id_survey';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_by_status($status)
    {
        $this->db->where('status', $status);
        return $this->db->get($this->table)->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_survey', $q);
    	$this->db->or_like('id_provinsi', $q);
    	$this->db->or_like('id_kab_kota', $q);
    	$this->db->or_like('id_kecamatan', $q);
    	$this->db->or_like('tahun', $q);
    	$this->db->or_like('status', $q);
    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_survey', $q);
    	$this->db->or_like('id_provinsi', $q);
    	$this->db->or_like('id_kab_kota', $q);
    	$this->db->or_like('id_kecamatan', $q);
    	$this->db->or_like('tahun', $q);
    	$this->db->or_like('status', $q);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function get_provinsi()
    {
        $this->db->order_by('name', 'ASC');
        return $this->db->get('provinces')->result();
    }

    function get_kab_by_id_prov($id_prov)
    {
        $this->db->where('province_id', $id_prov);
        return $this->db->get('regencies')->result();
    }

    function get_kec_by_kab($kab)
    {
        $this->db->where('regency_id', $kab);
        return $this->db->get('districts')->result();
    }

    function get_desa_by_kec_id_survey($kec,$id_survey)
    {
        $sql = "     SELECT * 
                     FROM `villages` 
                     WHERE `district_id` = '".$kec."' 
                     AND `name` NOT IN (SELECT `survey_detail`.`nama_desa` FROM `survey_detail` WHERE `id_survey` = ".$id_survey." ) 
                ";
        $query = $this->db->query($sql);
        return $query->result();
    }

    function get_desa_by_kec($kec){
        $this->db->where('district_id', $kec);
        return $this->db->get('villages')->result();
    }

    function get_nama_prov($id)
    {
         $this->db->where('id', $id);
        return $this->db->get('provinces')->row();
    }

    function get_nama_kab($id)
    {
        $this->db->where('id', $id);
        return $this->db->get('regencies')->row();
    }

    function get_nama_kec($id)
    {
        $this->db->where('id', $id);
        return $this->db->get('districts')->row();
    }

    function get_nama_desa($id)
    {
        $this->db->where('id', $id);
        return $this->db->get('villages')->row();
    }



}

/* End of file Survey_model.php */
/* Location: ./application/models/Survey_model.php */
/* Please DO NOT modify this information : */
/* This file generated by Andre Bhaskoro (+62 82 333 817 317) At : 2016-09-29 10:59:24 */
/* http://bhas.web.id */